# PostgreSQL
DB_HOST=localhost
DB_PORT=5432
DB_NAME=pool_db
DB_USER=pool_admin
DB_PASSWORD=pool_admin_password

# VK Bot
GROUP_ID=237058626
VK_BOT_TOKEN=vk1.a.bXIAnXw9FrPinG_bY0yUkC_whKlIhct33A_d9Sgqpk3v0cE9C5yDFRYMWu9BeIx6fE3gj8VxYXWx8kWpnB7UU7kiTWLF6_uoniV05LtZI65vPmtiBC_M4FO6gHmKqoHl-bG56dDnf70j1IfDt_i7M3nxs0KgaK45Jpn0K-36OmXygM5aMQ_fbD0FhXXEP_sAy_xcjUnyFG-eK-qjF3aKcA

# Spring
SPRING_PROFILES_ACTIVE=dev
SERVER_PORT=8080

# Long Poll
LONG_POLL_TIMEOUT=25
DB_MAX_RETRIES=5
DB_RETRY_DELAY=5

# MinIO
MINIO_ENDPOINT=http://135.106.180.64:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin123
MINIO_BUCKET=medical-certificates
MINIO_DOCS_BUCKET=pool-documents


# --- ????????? ??? Spring Boot Admin Panel ---
spring.datasource.url=jdbc:postgresql://localhost:5432/pool_db
spring.datasource.username=pool_admin
spring.datasource.password=pool_admin_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ?????????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=pool

# ????????? ?????????????? ?????????? schema.sql, ??? ??? ?? ?????????? ???? init_db.sql
spring.sql.init.mode=never